import { IPaymentMethod } from "../interfaces";

export const paymentMethods: IPaymentMethod[] = [
  {
    id: "1",
    name: "American Express",
    icon: "/payment-icons/Assets/Credit Card/AmericanExpress/AmericanExpress.svg",
    details: false,
    qr: false,
  },
  {
    id: "2",
    name: "Cirrus",
    icon: "/payment-icons/Assets/Credit Card/Cirrus/Cirrus.svg",
    details: false,
    qr: false,
  },
  {
    id: "3",
    name: "Diners Club",
    icon: "/payment-icons/Assets/Credit Card/DinersClub/DinersClub.svg",
    details: false,
    qr: false,
  },
  {
    id: "4",
    name: "Discover",
    icon: "/payment-icons/Assets/Credit Card/Discover/Discover.svg",
    details: false,
    qr: false,
  },
  {
    id: "5",
    name: "JCB",
    icon: "/payment-icons/Assets/Credit Card/JCB/JCB.svg",
    details: false,
    qr: false,
  },
  {
    id: "6",
    name: "Maestro",
    icon: "/payment-icons/Assets/Credit Card/Maestro/Maestro.svg",
    details: false,
    qr: false,
  },
  {
    id: "7",
    name: "MasterCard",
    icon: "/payment-icons/Assets/Credit Card/MasterCard/MasterCard.svg",
    details: false,
    qr: false,
  },
  {
    id: "8",
    name: "UnionPay",
    icon: "/payment-icons/Assets/Credit Card/UnionPay/UnionPay.svg",
    details: false,
    qr: false,
  },
  {
    id: "9",
    name: "Visa",
    icon: "/payment-icons/Assets/Credit Card/Visa/Visa.svg",
    details: false,
    qr: false,
  },
  {
    id: "10",
    name: "2checkout",
    icon: "/payment-icons/Assets/Payment/2checkout/2checkout.svg",
    details: false,
    qr: false,
  },
  {
    id: "11",
    name: "AliPay",
    icon: "/payment-icons/Assets/Payment/AliPay/AliPay.svg",
    details: false,
    qr: false,
  },
  {
    id: "12",
    name: "Amazon",
    icon: "/payment-icons/Assets/Payment/Amazon/Amazon.svg",
    details: false,
    qr: false,
  },
  {
    id: "13",
    name: "Apple Pay",
    icon: "/payment-icons/Assets/Payment/Apple/Apple.svg",
    details: false,
    qr: false,
  },
  {
    id: "14",
    name: "Bancontact",
    icon: "/payment-icons/Assets/Payment/Bancontact/Bancontact.svg",
    details: false,
    qr: false,
  },
  {
    id: "15",
    name: "Bitcoin",
    icon: "/payment-icons/Assets/Payment/Bitcoin/Bitcoin.svg",
    details: true,
    qr: true,
  },
  {
    id: "16",
    name: "Bitpay",
    icon: "/payment-icons/Assets/Payment/Bitpay/Bitpay.svg",
    details: false,
    qr: false,
  },
  {
    id: "17",
    name: "Clickandbuy",
    icon: "/payment-icons/Assets/Payment/Clickandbuy/Clickandbuy.svg",
    details: false,
    qr: false,
  },
  {
    id: "18",
    name: "Coinkite",
    icon: "/payment-icons/Assets/Payment/Coinkite/Coinkite.svg",
    details: false,
    qr: false,
  },
  {
    id: "19",
    name: "Direct Debit",
    icon: "/payment-icons/Assets/Payment/DirectDebit/DirectDebit.svg",
    details: false,
    qr: false,
  },
  {
    id: "20",
    name: "Dwolla",
    icon: "/payment-icons/Assets/Payment/Dwolla/Dwolla.svg",
    details: false,
    qr: false,
  },
  {
    id: "22",
    name: "Eway",
    icon: "/payment-icons/Assets/Payment/Eway/Eway.svg",
    details: false,
    qr: false,
  },
  {
    id: "23",
    name: "GiroPay",
    icon: "/payment-icons/Assets/Payment/GiroPay/GiroPay.svg",
    details: false,
    qr: false,
  },
  {
    id: "24",
    name: "Google Wallet",
    icon: "/payment-icons/Assets/Payment/GoogleWallet/GoogleWallet.svg",
    details: false,
    qr: false,
  },

  {
    id: "26",
    name: "Klarna",
    icon: "/payment-icons/Assets/Payment/Klarna/Klarna.svg",
    details: false,
    qr: false,
  },
  {
    id: "27",
    name: "Laser",
    icon: "/payment-icons/Assets/Payment/Laser/Laser.svg",
    details: false,
    qr: false,
  },
  {
    id: "28",
    name: "Monero",
    icon: "/payment-icons/Assets/Payment/Monero/Monero.svg",
    details: true,
    qr: false,
  },
  {
    id: "29",
    name: "Neteller",
    icon: "/payment-icons/Assets/Payment/Neteller/Neteller.svg",
    details: false,
    qr: false,
  },
  {
    id: "30",
    name: "Ogone",
    icon: "/payment-icons/Assets/Payment/Ogone/Ogone.svg",
    details: false,
    qr: false,
  },
  {
    id: "31",
    name: "OkPay",
    icon: "/payment-icons/Assets/Payment/OkPay/OkPay.svg",
    details: false,
    qr: false,
  },
  {
    id: "32",
    name: "PayPal",
    icon: "/payment-icons/Assets/Payment/PayPal/PayPal.svg",
    details: true,
    qr: false,
  },
  {
    id: "33",
    name: "PayU",
    icon: "/payment-icons/Assets/Payment/PayU/PayU.svg",
    details: false,
    qr: false,
  },
  {
    id: "34",
    name: "Paybox",
    icon: "/payment-icons/Assets/Payment/Paybox/Paybox.svg",
    details: false,
    qr: false,
  },
  {
    id: "35",
    name: "Paymill",
    icon: "/payment-icons/Assets/Payment/Paymill/Paymill.svg",
    details: false,
    qr: false,
  },
  {
    id: "36",
    name: "Payone",
    icon: "/payment-icons/Assets/Payment/Payone/Payone.svg",
    details: false,
    qr: false,
  },
  {
    id: "38",
    name: "PaysafeCard",
    icon: "/payment-icons/Assets/Payment/PaysafeCard/PaysafeCard.svg",
    details: false,
    qr: false,
  },
  {
    id: "39",
    name: "Payza",
    icon: "/payment-icons/Assets/Payment/Payza/Payza.svg",
    details: false,
    qr: false,
  },
  {
    id: "40",
    name: "Ripple",
    icon: "/payment-icons/Assets/Payment/Ripple/Ripple.svg",
    details: true,
    qr: false,
  },
  {
    id: "41",
    name: "Sage",
    icon: "/payment-icons/Assets/Payment/Sage/Sage.svg",
    details: false,
    qr: false,
  },
  {
    id: "42",
    name: "Sepa",
    icon: "/payment-icons/Assets/Payment/Sepa/Sepa.svg",
    details: false,
    qr: false,
  },
  {
    id: "43",
    name: "Shopify",
    icon: "/payment-icons/Assets/Payment/Shopify/Shopify.svg",
    details: false,
    qr: false,
  },
  {
    id: "45",
    name: "Solo",
    icon: "/payment-icons/Assets/Payment/Solo/Solo.svg",
    details: false,
    qr: false,
  },
  {
    id: "46",
    name: "Square",
    icon: "/payment-icons/Assets/Payment/Square/Square.svg",
    details: false,
    qr: false,
  },
  {
    id: "47",
    name: "Stripe",
    icon: "/payment-icons/Assets/Payment/Stripe/Stripe.svg",
    details: false,
    qr: false,
  },
  {
    id: "48",
    name: "Switch",
    icon: "/payment-icons/Assets/Payment/Switch/Switch.svg",
    details: false,
    qr: false,
  },
  {
    id: "49",
    name: "Ukash",
    icon: "/payment-icons/Assets/Payment/Ukash/Ukash.svg",
    details: false,
    qr: false,
  },
  {
    id: "52",
    name: "WebMoney",
    icon: "/payment-icons/Assets/Payment/WebMoney/WebMoney.svg",
    details: false,
    qr: false,
  },
  {
    id: "53",
    name: "Western Union",
    icon: "/payment-icons/Assets/Payment/WesternUnion/WesternUnion.svg",
    details: false,
    qr: false,
  },
  {
    id: "54",
    name: "WorldPay",
    icon: "/payment-icons/Assets/Payment/WorldPay/WorldPay.svg",
    details: false,
    qr: false,
  },
  {
    id: "55",
    name: "WeChat Pay",
    icon: "/payment-logos/svg/color/wechat_pay.svg",
    details: true,
    qr: true,
  },
];
